apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{.Chart.Name}}-deployment-{{.Values.environment}}
 labels:
  app: {{.Chart.Name}}-deployment-{{.Values.environment}}

spec:
  selector:
    matchLabels:
      app: {{.Chart.Name}}-deployment-{{.Values.environment}}

  template:
    metadata:
      labels:
        app: {{.Chart.Name}}-deployment-{{.Values.environment}}

    spec:
     containers:
       - name : {{.Chart.Name}}-{{.Values.pod.containerName}}-{{.Values.environment}}
         image: {{.Values.pod.imageName}}
         ports:
          - containerPort : {{.Values.pod.containerPort}} #this should match the port nginx listening on
         volumeMounts:
         - name: {{.Values.config.volume}}
           mountPath: /{{.Values.config.mountPath}}
           readOnly: true
         - name : {{.Values.secret.volume}}
           mountPath: /{{.Values.secret.mountPath}}
           readOnly: true
     volumes:
     - name: {{.Values.config.volume}}
       configMap:
         name: {{.Values.environment}}-{{.Values.config.name}}
     - name : {{.Values.secret.volume}}
       secret:
         secretName: {{.Values.secret.name}}

# Secret created manually
#C:\Users\User>kubectl create secret generic firstsecret --from-literal pwd=foo
#secret/firstsecret created


#helm install helm-release helm-test
#helm upgrade helm-release helm-test