
pod:
 containerName: "container"
 imageName: ""
 containerPort: 80
 volume: config-vol
 mountPath: config

services:
  name: "service"
  type: NodePort  #due to external IP pending issue, changed from LoadBalancer to NodePort
  app:
   dev: 8086
   uat: 8087
   prod: 8088

  node:
    dev: 31508
    uat: 31509
    prod: 31510

environment: ""

config: 
  name: app-micro-front-end-1-config
  volume: app-micro-front-end-1-config-vol
  mountPath: config
