
pod:
 containerName: "container"
 imageName: ""
 containerPort: 80
 volume: config-vol
 mountPath: config

services:
  name: "service"
  type: NodePort  #due to external IP pending issue, changed from LoadBalancer to NodePort
  devAppPort: 8086
  uatAppPort: 8087
  prodAppPort: 8088
  nodeDevPort: 31508

environment: ""

config: 
  name: app-micro-element-config
  volume: app-micro-element-config-vol
  mountPath: config
